services:
  - type: web
    name: ncert-rag-api
    runtime: docker
    repo: https://github.com/AshutoshGitMirror/ncert-rag
    plan: free
    region: singapore
    envVars:
      - key: INDEX_URL
        value: https://github.com/AshutoshGitMirror/ncert-rag/releases/download/v1
      - key: PORT
        value: "8000"
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
    healthCheckPath: /health
